'use client'

import { useCallback, useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import Link from 'next/link'
import { ChevronLeft, Loader2, Eye, Save, CheckCircle2, AlertTriangle } from 'lucide-react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { cn } from '@/lib/utils'
import type { ReportTemplate, SlotDefinition } from '@/lib/types'

// ─── Step indicators ──────────────────────────────────────────────────────────

const STEPS = ['Fill Slots', 'Preview', 'Save'] as const
type Step = 0 | 1 | 2

// ─── Slot input ───────────────────────────────────────────────────────────────

function SlotInput({
  slot,
  value,
  onChange,
}: {
  slot: SlotDefinition
  value: string
  onChange: (v: string) => void
}) {
  if (slot.data_source === 'navhub_financial') {
    return (
      <p className="text-xs text-muted-foreground italic px-3 py-2 border rounded-md bg-muted/30">
        Will be fetched automatically from NavHub financial data
      </p>
    )
  }
  if (slot.data_source === 'agent_provided') {
    return (
      <p className="text-xs text-muted-foreground italic px-3 py-2 border rounded-md bg-muted/30">
        Will be generated by the AI agent
      </p>
    )
  }
  if (slot.data_source === 'uploaded_file') {
    return (
      <p className="text-xs text-muted-foreground italic px-3 py-2 border rounded-md bg-muted/30">
        Will be sourced from an uploaded file
      </p>
    )
  }

  // Manual input
  if (slot.type === 'color') {
    return (
      <input
        type="color"
        value={value || '#000000'}
        onChange={e => onChange(e.target.value)}
        className="h-9 w-20 rounded-md border bg-background cursor-pointer"
      />
    )
  }
  if (slot.type === 'number') {
    return (
      <input
        type="number"
        value={value}
        onChange={e => onChange(e.target.value)}
        className="w-full px-3 py-2 rounded-md border bg-background text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-primary/50"
      />
    )
  }
  if (slot.type === 'date') {
    return (
      <input
        type="date"
        value={value}
        onChange={e => onChange(e.target.value)}
        className="w-full px-3 py-2 rounded-md border bg-background text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-primary/50"
      />
    )
  }
  if (slot.type === 'html' || slot.type === 'table' || slot.type === 'list' || slot.type === 'object') {
    return (
      <textarea
        value={value}
        onChange={e => onChange(e.target.value)}
        rows={5}
        placeholder={slot.type === 'object' || slot.type === 'table' || slot.type === 'list'
          ? 'Enter JSON...'
          : 'Enter HTML...'}
        className="w-full px-3 py-2 rounded-md border bg-background text-foreground text-sm font-mono focus:outline-none focus:ring-2 focus:ring-primary/50 resize-y"
      />
    )
  }
  // text
  return (
    <input
      type="text"
      value={value}
      onChange={e => onChange(e.target.value)}
      className="w-full px-3 py-2 rounded-md border bg-background text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-primary/50"
    />
  )
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function GenerateReportPage() {
  const params     = useParams()
  const router     = useRouter()
  const templateId = params?.id as string

  const [template,   setTemplate]   = useState<ReportTemplate | null>(null)
  const [loading,    setLoading]    = useState(true)
  const [error,      setError]      = useState<string | null>(null)
  const [step,       setStep]       = useState<Step>(0)
  const [slotValues, setSlotValues] = useState<Record<string, string>>({})
  const [previewHtml, setPreviewHtml] = useState<string | null>(null)
  const [previewLoading, setPreviewLoading] = useState(false)
  const [missingSlots, setMissingSlots]     = useState<string[]>([])
  const [reportName, setReportName] = useState('')
  const [notes,      setNotes]      = useState('')
  const [saving,     setSaving]     = useState(false)

  const load = useCallback(async () => {
    try {
      const res  = await fetch(`/api/report-templates/${templateId}`)
      const json = await res.json()
      if (!res.ok) throw new Error(json.error ?? 'Not found')
      const tpl: ReportTemplate = json.data
      setTemplate(tpl)
      setReportName(tpl.name)
      // Init slot values with defaults
      const defaults: Record<string, string> = {}
      for (const slot of tpl.slots) {
        defaults[slot.name] = slot.default !== undefined ? String(slot.default) : ''
      }
      setSlotValues(defaults)
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Error')
    } finally {
      setLoading(false)
    }
  }, [templateId])

  useEffect(() => { load() }, [load])

  function buildSlotData(): Record<string, unknown> {
    const data: Record<string, unknown> = {}
    for (const [key, val] of Object.entries(slotValues)) {
      // Try parsing JSON for object/table/list types
      const slot = template?.slots.find(s => s.name === key)
      if (slot && ['object', 'table', 'list'].includes(slot.type)) {
        try { data[key] = JSON.parse(val) } catch { data[key] = val }
      } else {
        data[key] = val
      }
    }
    return data
  }

  async function handlePreview() {
    if (!template) return
    setPreviewLoading(true)
    try {
      const res  = await fetch(`/api/report-templates/${templateId}/render`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ slot_data: buildSlotData() }),
      })
      const json = await res.json()
      if (!res.ok) throw new Error(json.error)
      setPreviewHtml(json.data.html)
      setMissingSlots(json.data.missing_slots ?? [])
      setStep(1)
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Preview failed')
    } finally {
      setPreviewLoading(false)
    }
  }

  async function handleSave() {
    if (!template) return
    setSaving(true)
    try {
      const res = await fetch(`/api/report-templates/${templateId}/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          slot_data:   buildSlotData(),
          report_name: reportName,
          notes,
        }),
      })
      const json = await res.json()
      if (!res.ok) throw new Error(json.error ?? 'Save failed')
      router.push('/reports/custom')
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Save failed')
    } finally {
      setSaving(false)
    }
  }

  // ── Render ──

  if (loading) {
    return (
      <div className="flex items-center justify-center h-48">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    )
  }

  if (error && !template) {
    return (
      <div className="space-y-3">
        <Link href="/reports/templates" className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground">
          <ChevronLeft className="h-4 w-4" /> Back
        </Link>
        <p className="text-sm text-destructive">{error}</p>
      </div>
    )
  }

  const manualSlots = template?.slots.filter(s => s.data_source === 'manual') ?? []

  return (
    <div className="max-w-2xl space-y-6">
      {/* Header */}
      <div className="flex items-center gap-3">
        <button
          onClick={() => {
            if (step === 0) router.push(`/reports/templates/${templateId}`)
            else setStep((step - 1) as Step)
          }}
          className="text-muted-foreground hover:text-foreground transition-colors"
        >
          <ChevronLeft className="h-5 w-5" />
        </button>
        <div>
          <h1 className="text-xl font-bold text-foreground">Generate Report</h1>
          <p className="text-xs text-muted-foreground">From: {template?.name}</p>
        </div>
      </div>

      {/* Step indicator */}
      <div className="flex items-center gap-0">
        {STEPS.map((s, i) => (
          <div key={s} className="flex items-center">
            <div className={cn(
              'flex items-center justify-center w-7 h-7 rounded-full text-xs font-bold border-2 transition-colors',
              step > i  ? 'border-primary bg-primary text-white'   :
              step === i ? 'border-primary text-primary bg-primary/10' :
                           'border-border text-muted-foreground bg-background'
            )}>
              {step > i ? <CheckCircle2 className="h-4 w-4" /> : i + 1}
            </div>
            <span className={cn(
              'ml-2 text-xs font-medium',
              step === i ? 'text-primary' : 'text-muted-foreground'
            )}>
              {s}
            </span>
            {i < STEPS.length - 1 && (
              <div className={cn('mx-3 h-0.5 w-8', step > i ? 'bg-primary' : 'bg-border')} />
            )}
          </div>
        ))}
      </div>

      {/* ── Step 0: Fill Slots ── */}
      {step === 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="text-sm">Fill Slot Values</CardTitle>
            <CardDescription>
              Provide values for each manual slot. Auto-filled slots will be resolved during generation.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-5">
            {template?.slots.map(slot => (
              <div key={slot.name} className="space-y-1.5">
                <div className="flex items-start justify-between gap-2">
                  <label className="text-sm font-medium text-foreground">
                    {slot.label}
                    {slot.required && <span className="text-destructive ml-1">*</span>}
                  </label>
                  <span className="text-xs text-muted-foreground shrink-0">{slot.type}</span>
                </div>
                {slot.description && (
                  <p className="text-xs text-muted-foreground">{slot.description}</p>
                )}
                <SlotInput
                  slot={slot}
                  value={slotValues[slot.name] ?? ''}
                  onChange={v => setSlotValues(prev => ({ ...prev, [slot.name]: v }))}
                />
              </div>
            ))}

            {template?.slots.length === 0 && (
              <p className="text-sm text-muted-foreground">This template has no slots to fill.</p>
            )}

            {error && (
              <div className="flex items-center gap-2 text-sm text-destructive">
                <AlertTriangle className="h-4 w-4 shrink-0" />
                {error}
              </div>
            )}

            <div className="flex justify-end pt-2">
              <button
                onClick={handlePreview}
                disabled={previewLoading}
                className="flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium text-white disabled:opacity-60"
                style={{ backgroundColor: 'var(--palette-primary)' }}
              >
                {previewLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Eye className="h-4 w-4" />}
                Preview
              </button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* ── Step 1: Preview ── */}
      {step === 1 && previewHtml && (
        <div className="space-y-4">
          {missingSlots.length > 0 && (
            <div className="flex items-start gap-2 p-3 rounded-md bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800">
              <AlertTriangle className="h-4 w-4 text-amber-600 shrink-0 mt-0.5" />
              <p className="text-sm text-amber-700 dark:text-amber-300">
                Missing required slots: {missingSlots.join(', ')}
              </p>
            </div>
          )}

          <Card className="overflow-hidden">
            <CardHeader>
              <CardTitle className="text-sm">Preview</CardTitle>
              <CardDescription>This is how the generated report will look.</CardDescription>
            </CardHeader>
            <CardContent className="p-0">
              <iframe
                srcDoc={previewHtml}
                className="w-full border-0"
                style={{ height: '600px' }}
                sandbox="allow-scripts allow-same-origin"
                title="Report preview"
              />
            </CardContent>
          </Card>

          <div className="flex items-center justify-between">
            <button
              onClick={() => setStep(0)}
              className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"
            >
              <ChevronLeft className="h-4 w-4" /> Edit slots
            </button>
            <button
              onClick={() => setStep(2)}
              className="flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium text-white"
              style={{ backgroundColor: 'var(--palette-primary)' }}
            >
              Continue to Save
            </button>
          </div>
        </div>
      )}

      {/* ── Step 2: Save ── */}
      {step === 2 && (
        <Card>
          <CardHeader>
            <CardTitle className="text-sm">Save to Reports Library</CardTitle>
            <CardDescription>
              The generated report will be saved to the Custom Reports Library.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-foreground">Report Name <span className="text-destructive">*</span></label>
              <input
                type="text"
                value={reportName}
                onChange={e => setReportName(e.target.value)}
                className="w-full px-3 py-2 rounded-md border bg-background text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-primary/50"
              />
            </div>
            <div className="space-y-1.5">
              <label className="text-sm font-medium text-foreground">Notes <span className="text-muted-foreground">(optional)</span></label>
              <textarea
                value={notes}
                onChange={e => setNotes(e.target.value)}
                rows={3}
                className="w-full px-3 py-2 rounded-md border bg-background text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-primary/50 resize-none"
              />
            </div>

            {error && (
              <div className="flex items-center gap-2 text-sm text-destructive">
                <AlertTriangle className="h-4 w-4 shrink-0" />
                {error}
              </div>
            )}

            <div className="flex items-center justify-between pt-2">
              <button
                onClick={() => setStep(1)}
                className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"
              >
                <ChevronLeft className="h-4 w-4" /> Back to preview
              </button>
              <button
                onClick={handleSave}
                disabled={saving || !reportName.trim()}
                className="flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium text-white disabled:opacity-60"
                style={{ backgroundColor: 'var(--palette-primary)' }}
              >
                {saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
                Save Report
              </button>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  )
}
